### ISSUE TITLE
ACTIVIDAD 10 MOCKUP DE LA APLICACION WEB 3.0 "MERCADO PARA TODOS"

### ISSUE THREAD

**Issue by YaelTrinidad** [SistemasTecTlaxiaco/actividad-10-mockup-de-aplicacion-web-3-equipo-2#1]
https://www.figma.com/file/p7B0LYkubkxNxnPTRogwZP/Untitled?node-id=145%3A303&t=tPvKBKPVQcZ4g94N-0

**Comment by Blanca-estela-valerio-rivero** [comment]
Obtuvo los 12 puntos ,que equivale al 50%, de acuerdo con la rubrica.

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
